# Generated by Django 4.0.6 on 2022-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ip_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpPools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=64, null=True)),
                ('stb_mac', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ip_pools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManyStb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'many_stb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsanRegionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nename', models.CharField(blank=True, db_column='NeName', max_length=128, null=True)),
                ('neip', models.CharField(blank=True, db_column='NeIP', max_length=128, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'msan_region_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mac_add', models.CharField(db_column='Mac_add', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
            ],
            options={
                'db_table': 'phone_nr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=64, null=True)),
                ('stb_mac', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radacct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('realm', models.CharField(blank=True, max_length=64, null=True)),
                ('nasipaddress', models.CharField(max_length=15)),
                ('nasportid', models.CharField(blank=True, max_length=15, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctsessiontime', models.PositiveIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=50, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=50, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(max_length=50)),
                ('callingstationid', models.CharField(max_length=50)),
                ('acctterminatecause', models.CharField(max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.CharField(max_length=15)),
                ('acctstartdelay', models.PositiveIntegerField(blank=True, null=True)),
                ('acctstopdelay', models.PositiveIntegerField(blank=True, null=True)),
                ('xascendsessionsvrkey', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radpostauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('pass_field', models.CharField(db_column='pass', max_length=64)),
                ('reply', models.CharField(max_length=32)),
                ('authdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radusergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('subnet', models.CharField(blank=True, max_length=64, null=True)),
                ('gateway', models.CharField(blank=True, max_length=64, null=True)),
                ('network', models.CharField(blank=True, max_length=64, null=True)),
                ('dns', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StbMacHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=64, null=True)),
                ('stb_mac', models.CharField(blank=True, max_length=64, null=True)),
                ('date_deleted', models.DateTimeField()),
            ],
            options={
                'db_table': 'stb_mac_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpUser',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tmp_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userId')),
                ('username', models.CharField(max_length=32)),
                ('userip', models.CharField(db_column='userIp', max_length=45)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('logtime', models.DateTimeField(db_column='logTime')),
            ],
            options={
                'db_table': 'userlog',
                'managed': False,
            },
        ),
    ]
